Traceback (most recent call last):
  File "/tmp/ipykernel_174158/162154560.py", line 3, in <cell line: 2>
    raise Exception('This is the error message.')
Exception: This is the error message.
